name: flutter_monet_theme
description: An package for creating monet themes in flutter with an friendly api
version: 0.4.4
homepage: https://github.com/KalilDev/material_theme_reverse

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  monet_theme: ^0.4.2
  material_color_utilities: ^0.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: